### ISSUE TITLE
Bug, Invalid token of mangarock, and failing to convert string to json object error.

### ISSUE THREAD

**Issue by Sohil876** [arkon/tachirock#1]
The id of mangarock needs to be replaced imho, default 1554176584893433600 to 1554176584893433663.
Then after that importing it fails on tachiyomi giving: "Value Invalid request at data of type java.lang.String cannot be converted to JSONObject" on every manga, example log "The "Hentai" Prince and the Stony Cat. - Value Invalid request at data of type java.lang.String cannot be converted to JSONObject" error, pls fix.

**Comment by arkon** [comment]
It'd help if you provided your JSON (either from MR or the tool).

Tbh I'm not even sure where the JSON from MR comes from, I just built this based on one guy's file.

**Comment by Sohil876** [comment]
Its a random named zip file in /data/data/com.notabasement.mangarock.android.lotus/ when you create a backup, afaik its name goes like this (some random string of text,characters and numbers)_backup.zip.

**Comment by arkon** [comment]
I changed the ID to `1554176584893433600`. I assume that's the ID of DummyRock? Trying to restore to the MangaRock extension would be futile at this point (evidently, based on that error message).

**Comment by Sohil876** [comment]
> I changed the ID to `1554176584893433600`. I assume that's the ID of Dummy Rock? Trying to restore to the MangaRock extension would be futile at this point (evidently, based on that error message).
> 
> EDIT: I realized the IDs differed between the actual code and the README. It was meant to be the Manga Rock extension. I don't know what the Dummy Rock extension's ID is.

Yup, but the main problem is your tools json giving "cannot be converted to JSONObject" error, btw i hv converter mr's json that imports sucessfully into tachiyomi using mr2tachiyomi, so maybe just use json generated by that tool as reference.

**Comment by arkon** [comment]
This tool used the same ID as mr2tachiyomi. You can't use the Manga Rock extension anymore since it won't work at all at this point — you'd need to use Dummy Rock to import them.

If you need help with that, ask for help in the Tachiyomi Discord server.

**Comment by Sohil876** [comment]
> This tool used the same ID as mr2tachiyomi. You can't use the Manga Rock extension anymore since it won't work at all at this point — you'd need to use Dummy Rock to import them.
> 
> If you need help with that, ask for help in the Tachiyomi Discord server.

My problem is not the id, but the json file that your tool produces cannot be imported to tachiyomi because of the error ive posted in my first post, the main problem is that, i know about the id.

**Comment by arkon** [comment]
I'm 95% sure it's because you're trying to restore while using the regular Manga Rock extension. Can you confirm whether that's the case?

**Comment by Sohil876** [comment]
> I'm 95% sure it's because you're trying to restore while using the regular Manga Rock extension. Can you confirm whether that's the case?

Hmm can be, just to be sure your tool now puts dummyrocks id instead of mr by default right?

**Comment by arkon** [comment]
The IDs should be the same. I don't know what you mean by "default".

**Comment by Sohil876** [comment]
> The IDs should be the same. I don't know what you mean by "default".

By default i mean the id your tool assigns to the source, specifically this -> "1554176584893433600", i think this is mangarocks id, mangarocks extension is now dropped so itll give source not installed error with this id. Anyways i tried again but it still gave me the source not installed error (specified why before) with your tool and its default id, however this time when i replaced the default id 1554176584893433600 to 1554176584893433663 (the id used currently by mr2tachiyomi), with dummyrock extension installed ofc like before, it finally got restored sucessfully, no json error!. So maybe just change that id and post the good news in the migration thread of reddit? Ive already told you where mangarocks backup json file is, gr8 work 👍

**Comment by arkon** [comment]
I still have no idea what you're talking about. The ID was always the Manga Rock ID. It was wrong in the README though, which I've since updated.

**Comment by Sohil876** [comment]
> I still have no idea what you're talking about. The ID was always the Manga Rock ID. It was wrong in the README though, which I've since updated.

I cant beleive how can you not understand what im saying. It'll be faster this way, try generating a json through your own tool and try importing it in tachiyomi with dummyrock extention installed, however make sure youve uninstalled mangarock extension if you already have that installed, tachiyomi will give you a source not installed error even when you have dummyrock installed.

**Comment by arkon** [comment]
The ID was always `1554176584893433663`, which is the ID of both the Manga Rock and DUmmy Rock extensions, as well as used by mr2tachiyomi for that reason.

https://github.com/arkon/tachirock/blob/master/script.js#L61

**Comment by Sohil876** [comment]
> The ID was always `1554176584893433663`, which is the ID of both the Manga Rock and Dummy Rock extensions, as well as used by mr2tachiyomi for that reason.
> 
> https://github.com/arkon/tachirock/blob/master/script.js#L61

Wait is your online tool not updated by any chance?

**Comment by arkon** [comment]
Whatever's in the `master` branch is reflected on the deployed version (via GitHub pages). I really do have no idea what you're on about.

**Comment by Sohil876** [comment]
> Whatever's in the `master` branch is reflected on the deployed version (via GitHub pages). I really do have no idea what you're on about.

Uh, heres a freshly converted json and you can see the id by yourself... https://drive.google.com/file/d/1-o5laU_GO-lsgySS62c7xBth5r8DTLvb/view?usp=drivesdk

**Comment by arkon** [comment]
Alright, I finally understood what you meant.

It was an issue with how JavaScript handles large numbers. It should be fixed now.

**Comment by Sohil876** [comment]
> Alright, I finally understood what you meant.
> 
> It was an issue with how JavaScript handles large numbers. It should be fixed now.

Thats true but my issue was browser cache

> Alright, I finally understood what you meant.
> 
> It was an issue with how JavaScript handles large numbers. It should be fixed now.

It turns out i had to clear cache of my browser 🤦 it was the one causing that weird id problem sorry my bad, but anyways i tested it right now and tachirock works flawlessly, gr8 work 👍
